### ISSUE TITLE
Debugger operation failed.

### ISSUE THREAD

**Issue by xarbit** [directhex/monodevelop-flatpak#4]
Installed the Monodevelop Flatpak, created a new .Net Console Project and I cannot debug it.
Get this error:

Debugger operation failed
Cannot start process because a file name has not been provided.

![image](https://cloud.githubusercontent.com/assets/590307/26827669/a0b98498-4abe-11e7-84be-d15f20d1349d.png)

See here:
https://bugzilla.xamarin.com/show_bug.cgi?id=56869
and here:
https://stackoverflow.com/questions/40159145/monodevelop-cannot-execute-project#41578645

**Comment by dmbarbour** [comment]
Can confirm. Just tried MonoDevelop via Flatpak (v 7.0.1 build 24), started the F# tutorial, hit the Run button. Same message. 

This was my first attempt to use MonoDevelop. It will probably also be my last.

**Comment by henriquecrw** [comment]
At the same issue, looking for some solution.

**Comment by terrapass** [comment]
Also affected by this issue.

As a temporary workaround, you can go to your project's options and un-check "Run on external console" in its run configuration settings. You will then be able to run and debug the project in MonoDevelop's internal console. The downside is that said console is non-interactive and so things like Console.ReadLine() won't work, but if your application only uses console for output, then everything should be fine.

**Comment by rad8329** [comment]
At the same issue, looking for some real solution.

**Comment by undauntedspirit** [comment]
Same issue here as well.  I'm really not liking flatpak, I understand the need for it, but... 

Almost three months later... and still nothing doesn't give me a whole lot of faith it'll be fixed either.... on to dotnet core I guess?

**Comment by katzio** [comment]
Currently, there is no external console application inside the flatpak container, so it is not possible to run on the external console.

Workaround: [uncheck the box that says "Run on external console"](https://stackoverflow.com/questions/43951799/console-project-fails-to-run-in-monodevelop-6-3-on-ubuntu)

Top Menu -> [*Solution Name*] -> Run -> Default -> uncheck the box that says "Run on external console"

![image](https://user-images.githubusercontent.com/4009104/29824206-88fbd65a-8cd9-11e7-9e9a-1ac7462c080f.png)

**Comment by lexx-admin** [comment]
It's sandbox bug. Disabling "run on external console" in project settings works around it.

**Comment by Pouya47** [comment]
This works
> It's sandbox bug. Disabling "run on external console" in project settings works around it.

But is there any fix for it?

**Comment by cbagpipe** [comment]
Can confirm this bug. Was so much confused yesterday!

**Comment by linclelinkpart5** [comment]
Confirming that this is still present as of 7.1 build 1291, when trying to run the F# tutorial bundled with the flatpak installation.

**Comment by ghost** [comment]
So if you want to write console applications with monodevelop you can't use the official flatpak release.

lol

**Comment by FireballDark** [comment]
Everyone who has the same issue, please refer to bug
https://bugzilla.xamarin.com/show_bug.cgi?id=44182

Developers say that it's fixed in alpha, you can install it using
flatpak install --user --from http://download.mono-project.com/repo/monodevelop-alpha.flatpakref

**Comment by RayKoopa** [comment]
Can confirm it's fixed in the current alpha version (7.2.2).

**Comment by akontsevich** [comment]
Yes, fixed however debug is running in / (root) directory, not the project directory. Bug? How to fix?

Temporarily fixed by `Directory.SetCurrentDirectory(AppDomain.CurrentDomain.BaseDirectory);`. Also alpha crashes after every program run/debug.

**P.S.** Also good we have Rider :)

**Comment by directhex** [comment]
Fix for this is in all published branches

**Comment by jboero** [comment]
My experience on this has been ugly as unmaintained regressions in Linux terminals break MonoDevelop external console support.  If you're using Linux, I have the following tips for workarounds which help all the way back to Monodevelop 5.9/5.10 which are still my favorite releases.  Unfortunately there is no "MANUAL" console command.  I've implemented it using an env variable but it's very hacky and probably not the best pull request.  Built-in console has never worked for me in Linux.

See the code here for more:
https://github.com/mono/monodevelop/blob/master/main/src/addins/GnomePlatform/GnomePlatform.cs

```
#!/bin/bash
# To force MonoDevelop to start in mate-terminal, which works best in my situation:
MATE_DESKTOP_SESSION_ID=1 /usr/bin/monodevelop &

# To force gnome terminal:
#GNOME_DESKTOP_SESSION_ID=1 /usr/bin/monodevelop &

# To force KDE, set KDE_SESSION_UID (unless you're using KDE)
# Note that Konsole support is broken with deprecated -caption flag hard-coded in MonoDevelop.
#KDE_SESSION_UID=1000 /usr/bin/monodevelop &

# To force xterm, unset them all

```

**Comment by toreaurstad** [comment]
Well, what helped me in MX Linux 17.1 was to install xterm to be able to debug a Mono console application. Looks like Mono supports not all terminals. There are other suggestions about running the Console project right clicking project in the Mono solution and selection Options =>  Run => General and selecting "Run on external console". Anyways, installing xterm lets me not only display the console app in a console, but also accepts ReadLine and ReadKey inputs from the keyboard. It would be nice if I could use a nicer console than boring xterm, but at least it works. MX Linux 17.1 uses Xfce4 and there is a lot of packages missing that I had to patch, like installing "apt-get install monodevel" in addition. What would be nice was a Monodevelop package that installed ALL the necessary packages to get up and running a console app right away, but there are so many Linux distros, so that challenge is not trivial.

**Comment by BelarminoVicenzo** [comment]
> 
> 
> This works
> 
> > It's sandbox bug. Disabling "run on external console" in project settings works around it.
> 
> But is there any fix for it?

Thank you very much.

**Comment by RayaneLehnemann** [comment]
How i found the most absurd solution to this bug!
1) Install the CodeBlocks
2) Write a Hello World in C++
3) Run the Hello World in Codeblocks
4) Then, your Monodevelop is fixed!

Original font: https://www.youtube.com/watch?v=BoQC7HS85Xo
Teste on Ubuntu 20.04

**Comment by ifratmitul** [comment]
The codeblock installing idea didn't fixed it still getting this:

ApplicationName='/usr/lib/gnome-terminal/gnome-terminal-server', CommandLine='--app-id mono.develop.ida7b6bd6fa9e44843b717bf619e9d7c51', CurrentDirectory='', Native error= Cannot find the specified file
